###
### 测试请求

###
GET http://localhost:8080/test


###
GET http://localhost:8080/test/selectListByExample


###
GET http://localhost:8080/test/1


###
PUT http://localhost:8080/test
Content-Type: application/json

{
  "id": 6,
  "create_time": "2020-07-07T06:07:15.000+00:00",
  "deleted": 0,
  "update_time": "2020-07-07T06:07:15.000+00:00",
  "city": "焦作",
  "country": "中国",
  "headimgurl": "https://cn.vuejs.org/images/logo.png",
  "language": "中文",
  "nickname": "小咩咩",
  "openid": "1214804270",
  "province": "河南",
  "sex": "1",
  "unionid": "1335282923"
}

###
POST http://localhost:8080/test
Content-Type: application/json

{
  "create_time": "2021-11-26T06:07:15.000+00:00",
  "deleted": 0,
  "update_time": "2021-11-26T06:07:15.000+00:00",
  "city": "北京",
  "country": "中国",
  "headimgurl": "https://cn.vuejs.org/images/logo.png",
  "language": "中文",
  "nickname": "小汪汪",
  "openid": "1214804270",
  "province": "河南",
  "sex": "1",
  "unionid": "1335282923"
}

###
DELETE http://localhost:8080/test/4

###
DELETE http://localhost:8080/test/deleteByPrimaryKeys/10,11,12